gh-83 [Feature] Automated feature branch for scheduled workflow (#86)
* gh-83 [Fix] Trying to make the scheduled workflow work

* gh-84 [Add] Automatic bumping version

* gh-84 [Change] Temporarily faking new tdlib version

* gh-84 [Fix] Version has been extracted somehow wrong

* gh-84 [Fix] Typo in the branch preparation script

* gh-84 [Change] Making the conditions work

* gh-84 [Change] Maybe or is better for the new branch creation condition

* gh-84 [Change] Dealing with the conditions

* gh-84 [Change] Getting rig of temporary things

diff --git a/.github/workflows/scheduled.yml b/.github/workflows/scheduled.yml
--- a/.github/workflows/scheduled.yml
+++ b/.github/workflows/scheduled.yml
@@ -8,6 +8,12 @@ on:
   schedule:
     - cron: '35 15 * * *'
   workflow_dispatch:
+    inputs:
+      prepare_changes:
+        required: true
+        default: false
+        type: boolean
+        description: Create feature branch
 
 jobs:
 
@@ -59,7 +65,7 @@ jobs:
           head -1
           )
 
-          echo "last_version=${LAST_VERSION}" >> "${GITHUB_OUTPUT}"
+          echo "last_version=${LAST_VERSION%*.}" >> "${GITHUB_OUTPUT}"
 
 
       - name: Match last tdlib version with .version contents
@@ -88,6 +94,34 @@ jobs:
           rest_gateway_url: "${{ secrets.REST_GATEWAY_API_URL }}"
           rest_gateway_token: "${{ secrets.REST_GATEWAY_TOKEN }}"
           rest_gateway_bot_name: "${{ secrets.REST_GATEWAY_BOT_NAME }}"
+
+
+      - name: Create a branch with a change for the found version
+        id: create_new_version_branch
+        if: steps.match_versions.outputs.match == 'true' or github.event.inputs.prepare_changes == 'true'
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+
+          git config --global user.name 'GitHub Actions'
+          git config --global user.email 'github-actions@local'
+
+          [[ -f .version ]] || { echo "Error: no .version file found"; exit 2; }
+
+          git checkout -b build_${{ steps.get_last_version.outputs.last_version }}
+          echo "${{ steps.get_last_version.outputs.last_version }}b" > .version
+
+          git add .version
+          git commit -a -m "gh-84 [Change] Automated version bump to ${{ steps.get_last_version.outputs.last_version }}"
+
+          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}
+          git push origin build_${{ steps.get_last_version.outputs.last_version }}
+
+          git status
+
+          gh pr create -B master -H build_${{ steps.get_last_version.outputs.last_version }} \
+            --title 'gh-84 [Change] Automated version bump to ${{ steps.get_last_version.outputs.last_version }}' \
+            --body 'v${{ steps.get_last_version.outputs.last_version }}'
 
 
       - name: Setup Terraform
@@ -122,13 +156,12 @@ jobs:
         env:
           TF_VAR_vultr_api_key: "${{ secrets.VULTR_API_KEY }}"
           TF_VAR_github_runners_count: 1
-        run: >-
-          terraform show -json |
-          jq -r '.values.outputs."instance-details".value[][] | .name + "\n" + .ipv4 + "\n" + .ipv6 + "\n"' >
+        run: |
+          terraform show -json | \
+          jq -r '.values.outputs."instance-details".value[][] | .name + "\n" + .ipv4 + "\n" + .ipv6 + "\n"' > \
           "outputs.json"
 
           cat outputs.json
-
           cat <<EOF >> "${GITHUB_OUTPUT}"
           instances<<EOF2
           $( cat outputs.json )
